Update National Director Position for Node.js Africa - Nigeria
nodejsafrica/members pull request #5
Opened 2018-06-25 20:09 UTC by codeekage

@OpesanyaAdebayo also update who will be assisting you to work.

2018-06-25 20:36 UTC, chukundah approved these changes

2018-06-26 19:56 UTC, inidaname requested changes
Node.js Nigeria - [Opesanya Adebayo](https://github.com/OpesanyaAdebayo) - National Director

**Sounds better if you add** 
Node.js Nigeria - [Opesanya Adebayo](https://github.com/OpesanyaAdebayo) - National Director, Nigeria.

2018-06-26 20:30 UTC, codeekage commented
@inidaname Please, feel free to make any changes

2018-06-26 20:34 UTC, inidaname approved these changes

2019-05-06 17:13 UTC, merged